const {chromium}=require('playwright');
const fs=require('fs');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || '/usr/bin/chromium',headless:true,args:['--no-sandbox']});
const page=await browser.newPage({acceptDownloads:true});
page.on('dialog',async d=>{console.log('Dialog:',d.message());await d.dismiss()});
const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('Page error:',e.message)});
if (process.env.RAILWAY_CDN_CACHE) {
const path=require('node:path');
await page.route('https://cdn.jsdelivr.net/npm/exceljs/dist/exceljs.min.js',r=>r.fulfill({path:path.join(process.env.RAILWAY_CDN_CACHE,'exceljs.js'),contentType:'application/javascript'}));
await page.route('https://cdn.jsdelivr.net/npm/xlsx/dist/xlsx.full.min.js',r=>r.fulfill({path:path.join(process.env.RAILWAY_CDN_CACHE,'xlsx.js'),contentType:'application/javascript'}));
}
await page.route('https://script.google.com/**',r=>r.abort());
page.setDefaultTimeout(10000);
await page.goto(process.env.RAILWAY_BASE_URL || 'http://127.0.0.1:8000');
await page.waitForFunction(()=>typeof XLSX!=='undefined'&&typeof ExcelJS!=='undefined');
const bytes=await page.evaluate(()=>{
 const headers=['Date','LocoID','Direction','StationCode','TagID','Time','LocoAbsLocation','Mode','TagLinkInfo','BrakeStatus','EmergencyStatus','LocoSpecificSOSSentByStn','SignalOverride','StationId','TrainSpeed','CurrentSignal','CurrentSignalAspect','StationName'];
 const base=['2026-10-07','39260','N','KANJ',388,'22:23:01',475100,'FS','','-','No Emergency','No SOS','',1,20,'S1','GREEN','KANJ'];
 const rows=[headers,base,base.map((v,i)=>i===5?'22:23:02':i===6?475103:i===7?'SR':v),base.map((v,i)=>i===5?'22:23:03':i===6?475110:v),base.map((v,i)=>i===3?'LC-246':i===5?'22:24:01':i===6?426104:i===8?'BOTH TAGS MISS':v),base.map((v,i)=>i===3?'VXD':i===5?'22:25:01':i===6?426200:i===9?'EB':v)];
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),'Input');return Array.from(new Uint8Array(XLSX.write(wb,{type:'array',bookType:'xlsx'})));
});
await page.locator('#trainNo').fill('20484');
await page.locator('#fileInput').setInputFiles({name:'smoke.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(bytes)});

const downloaded=page.waitForEvent('download');
await page.getByRole('button',{name:'Generate Final Excel'}).click();
const download=await downloaded;await download.saveAs('/tmp/railway-smoke-output.xlsx');
await page.locator('#reportPopup').waitFor();
const result=await page.evaluate(async bytes=>{
const wb=new ExcelJS.Workbook();await wb.xlsx.load(new Uint8Array(bytes));return {sheets:wb.worksheets.map(s=>s.name),rows:wb.worksheets[0].rowCount,log:document.querySelector('#log').textContent};
},Array.from(fs.readFileSync('/tmp/railway-smoke-output.xlsx')));
const assert=require('node:assert/strict');
assert.equal(result.rows,6);assert.equal(result.sheets.length,3);
await page.locator('#failureSummaryPopup').waitFor();
assert.equal(await page.locator('.summary-reasons input[type="text"]').count(),3);
await page.getByRole('textbox',{name:'Reason 1',exact:true}).fill('BJD Offline');
await page.getByRole('textbox',{name:'Reason 2',exact:true}).fill('Tag was removed at site');
await page.getByRole('textbox',{name:'Reason 3',exact:true}).fill('LC-258 dropped');
const values=await page.locator('.summary-grid td').allTextContents();
assert.match(values[3],/In Train No 20484 \/ Loco No 39260/);
assert.match(values[3],/Due to BJD Offline/);assert.ok(!values[3].includes('Mode transitions:'));assert.ok(!values[3].includes('475110'));assert.equal(await page.getByRole('checkbox').count(),8);assert.match(values[3],/Both Tags miss \(TAG - 388\) at LC-246/);assert.match(values[3],/EB applied at VXD/);
const boxes=await Promise.all([page.locator('.summary-grid td').first().boundingBox(),page.locator('.summary-grid td').last().boundingBox()]);
await page.mouse.move(boxes[0].x+10,boxes[0].y+10);await page.mouse.down();await page.mouse.move(boxes[1].x+10,boxes[1].y+10,{steps:10});await page.mouse.up();
assert.equal(await page.locator('.summary-grid td.selected').count(),4);
const copied=await page.evaluate(()=>{const data=new DataTransfer();const event=new ClipboardEvent('copy',{clipboardData:data,bubbles:true,cancelable:true});document.activeElement.dispatchEvent(event);return {html:data.getData('text/html'),plain:data.getData('text/plain')};});
assert.equal((copied.html.match(/<td /g)||[]).length,4);assert.match(copied.plain,/BJD Offline/);
await page.context().grantPermissions(['clipboard-read','clipboard-write']);
await page.getByRole('button',{name:'Copy row',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.summary-status').textContent.includes('Four cells copied'));
assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/BJD Offline/);
const editedDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download updated Excel'}).click();await (await editedDownload).saveAs('/tmp/railway-edited.xlsx');
const summaryValues=await page.evaluate(async bytes=>{const wb=new ExcelJS.Workbook();await wb.xlsx.load(new Uint8Array(bytes));return wb.getWorksheet('Failure Summary').getRow(2).values.slice(1);},Array.from(fs.readFileSync('/tmp/railway-edited.xlsx')));
assert.deepEqual(summaryValues,values);
await page.getByRole('button',{name:'Close',exact:true}).click();
await page.getByRole('button',{name:'✕ Cancel'}).click();
await page.getByRole('button',{name:'Failure Summary / Copy to Excel'}).click();assert.equal(await page.getByRole('textbox',{name:'Reason 1',exact:true}).inputValue(),'BJD Offline');
await page.getByRole('checkbox',{name:'Include incident 2',exact:true}).uncheck();
const checkboxAppearance=await page.getByRole('checkbox',{name:'Include incident 2',exact:true}).evaluate(el=>{
 const style=getComputedStyle(el),box=el.getBoundingClientRect();
 return {width:box.width,height:box.height,border:style.borderTopWidth,checked:el.checked};
});
assert.equal(checkboxAppearance.width,24);assert.equal(checkboxAppearance.height,24);
assert.equal(checkboxAppearance.border,'2px');assert.equal(checkboxAppearance.checked,false);
const filtered=await page.locator('.summary-grid td').allTextContents();
assert.equal(filtered[0],'1. BJD Offline\n2. LC-258 dropped');
assert.equal(filtered[1],'1. FS - SR\n2. EB');assert.equal(filtered[2],'1. KANJ\n2. VXD');
assert.ok(!filtered[3].includes('LC-246'));assert.match(filtered[3],/2\. EB applied/);
await page.getByRole('button',{name:'Copy row',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.summary-status').textContent.includes('Four cells copied'));
assert.ok(!(await page.evaluate(()=>navigator.clipboard.readText())).includes('LC-246'));
const filteredDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download updated Excel'}).click();await (await filteredDownload).saveAs('/tmp/railway-filtered.xlsx');
const filteredBook=await page.evaluate(async bytes=>{const wb=new ExcelJS.Workbook();await wb.xlsx.load(new Uint8Array(bytes));return {summary:wb.getWorksheet('Failure Summary').getRow(2).values.slice(1),observation:wb.getWorksheet('Nominal Observation Sheet').getCell('J4').value};},Array.from(fs.readFileSync('/tmp/railway-filtered.xlsx')));
assert.deepEqual(filteredBook.summary,filtered);assert.match(filteredBook.observation,/BOTH TAGS MISS/);
await page.getByRole('button',{name:'Close',exact:true}).click();
await page.getByRole('button',{name:'Failure Summary / Copy to Excel'}).click();
assert.equal(await page.getByRole('checkbox',{name:'Include incident 2',exact:true}).isChecked(),false);
assert.equal(await page.getByRole('textbox',{name:'Reason 2',exact:true}).inputValue(),'Tag was removed at site');
await page.getByRole('button',{name:'Clear all',exact:true}).click();
assert.match(await page.locator('.summary-grid td').last().textContent(),/No incidents selected/);
assert.equal(await page.locator('.summary-reasons input:checked').count(),0);
await page.getByRole('checkbox',{name:'Include incident 2',exact:true}).check();
assert.equal(await page.locator('.summary-grid td').first().textContent(),'1. Tag was removed at site');
await page.getByRole('button',{name:'Select all',exact:true}).click();
assert.deepEqual(await page.locator('.summary-grid td').allTextContents(),values);
console.log('PASS: checkbox filtering, renumbering, filtered clipboard and XLSX, unchanged observation entries, preserved selection and reasons, clear/select all.');
assert.deepEqual(errors,[]);
console.log('PASS: real incident generation; 3 incident reasons; four-cell drag and clipboard HTML/TSV; updated workbook reasons; reopen persistence; no JavaScript errors.');
await page.screenshot({path:'/tmp/railway-summary.png',fullPage:true});
await page.getByRole('button',{name:'Close',exact:true}).click();
const cleanBytes=await page.evaluate(bytes=>{
 const book=XLSX.read(new Uint8Array(bytes),{type:'array'});
 const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1});
 rows.slice(1).forEach(row=>{row[7]='FS';row[8]='';row[9]='-';row[10]='No Emergency';});
 book.Sheets[book.SheetNames[0]]=XLSX.utils.aoa_to_sheet(rows);
 return Array.from(new Uint8Array(XLSX.write(book,{type:'array',bookType:'xlsx'})));
},bytes);
await page.locator('#trainNo').fill('');
await page.locator('#fileInput').setInputFiles({name:'no-incidents.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(cleanBytes)});
const cleanDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Generate Final Excel'}).click();await cleanDownload;
await page.locator('#failureSummaryPopup').waitFor();
assert.equal(await page.locator('.summary-reasons input[type="text"]').count(),0);
assert.match(await page.locator('.summary-grid td').last().textContent(),/No incidents logged/);
assert.ok(!(await page.locator('.summary-grid td').last().textContent()).includes('BJD Offline'));
assert.deepEqual(errors,[]);
console.log('PASS: second generation with no incidents and blank train number clears prior reasons.');
await browser.close();
})().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
